services:
  zookeeper:
    image: zookeeper:3.7
    container_name: config-center-zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: "*"
    volumes:
      - zk_data:/data
      - zk_datalog:/datalog
    networks:
      - config-center-network

volumes:
  zk_data:
    driver: local
  zk_datalog:
    driver: local

networks:
  config-center-network:
    driver: bridge 