services:
  simple-container:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: simple-app-container
    hostname: simple-app
    ports:
      - "8081:8080"
    environment:
      - APP_NAME=simple-app
      - APP_VERSION=1.0.0
      - TZ=Asia/Shanghai
    volumes:
      - simple_data:/app/data
      - simple_logs:/app/logs
      - simple_config:/app/config
    networks:
      - simple-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  simple_data:
    driver: local
  simple_logs:
    driver: local
  simple_config:
    driver: local

networks:
  simple-network:
    driver: bridge 