services:
  virtual-container:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: virtual-app-container
    hostname: virtual-app
    ports:
      - "8080:8080"
    environment:
      - APP_NAME=virtual-app
      - APP_VERSION=1.0.0
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config
    networks:
      - virtual-network
    restart: unless-stopped

volumes:
  app_data:
    driver: local

networks:
  virtual-network:
    driver: bridge 