version: '3.8'

services:
  # 机器1
  machine-001:
    build:
      context: .
      dockerfile: Dockerfile.machine
    container_name: machine-001
    environment:
      - MACHINE_ID=machine-001
      - MACHINE_IP=192.168.1.1
    volumes:
      - ./machines/machine-001/config:/app/config
      - ./machines/machine-001/logs:/app/logs
    networks:
      - machine-network
    restart: unless-stopped

  # 机器2
  machine-002:
    build:
      context: .
      dockerfile: Dockerfile.machine
    container_name: machine-002
    environment:
      - MACHINE_ID=machine-002
      - MACHINE_IP=192.168.1.2
    volumes:
      - ./machines/machine-002/config:/app/config
      - ./machines/machine-002/logs:/app/logs
    networks:
      - machine-network
    restart: unless-stopped

  # 机器3
  machine-003:
    build:
      context: .
      dockerfile: Dockerfile.machine
    container_name: machine-003
    environment:
      - MACHINE_ID=machine-003
      - MACHINE_IP=192.168.1.3
    volumes:
      - ./machines/machine-003/config:/app/config
      - ./machines/machine-003/logs:/app/logs
    networks:
      - machine-network
    restart: unless-stopped

networks:
  machine-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24 