services:
  zookeeper:
    image: zookeeper:3.8.1
    container_name: config-center-zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_4LW_COMMANDS_WHITELIST: "*"
      ZOO_MAX_CLIENT_CNXNS: 60
    volumes:
      - zk_data:/data
      - zk_datalog:/datalog
    networks:
      - config-center-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "zkServer.sh", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  zk_data:
    driver: local
  zk_datalog:
    driver: local

networks:
  config-center-network:
    driver: bridge 